### PR TITLE
Fix error when JSON value is `null`

### PR DESCRIPTION
**Pull request by cgarvis**

### CODE REVIEW

**Comment by cmontella** [comment]
Fixes: https://github.com/witheve/Eve/issues/478

**Comment by xymostech** [comment]
As mentioned in #478, this would mean that the `null` value doesn't get recorded in the record at all, so de-serializing then serializing again might lose keys. I would love this merged though because it's painful not being able to use APIs that have `null`s in the responses.

**Comment by ibdknox** [comment]
Yeah, there's a follow up PR that needs to happen after this one that adds the sentinel value for json nulls.

**Comment by ibdknox** [comment]
Thanks!

**Pull request merged**
